package com.gruppe24.utils;

import javafx.scene.control.Button;

/**
 * {@code StyleUtils} is a utility class for styling buttons.
 */
public class StyleUtils {

  /**
   * Method to style the normal button.
   *
   * @AI_Assisted Some -fx- properties were suggested by the AI.
   */
  public static void styleNormalButton(Button normalButton) {
    String normalStyle =
        "-fx-background-color: #3a3aee;"
            + "-fx-text-fill: white;"
            + "-fx-padding: 10px 20px;"
            + "-fx-font-size: 16px;"
            + "-fx-border-radius: 5px;"
            + "-fx-border-color: #120B4E;"
            + "-fx-border-width: 3px;"
            + "-fx-background-radius: 5px;";

    String hoverStyle =
        "-fx-background-color: #5a5aff;"
            + "-fx-text-fill: white;"
            + "-fx-padding: 10px 20px;"
            + "-fx-font-size: 16px;"
            + "-fx-border-radius: 5px;"
            + "-fx-border-color: #120B4E;"
            + "-fx-border-width: 3px;"
            + "-fx-background-radius: 5px;";

    String pressedStyle =
        "-fx-background-color: #1C0F90;"
            + "-fx-text-fill: white;"
            + "-fx-padding: 10px 20px;"
            + "-fx-font-size: 16px;"
            + "-fx-border-radius: 5px;"
            + "-fx-border-color: #120B4E;"
            + "-fx-border-width: 3px;"
            + "-fx-background-radius: 5px;"
            + "-fx-translate-y: 2px;";

    normalButton.setStyle(normalStyle);

    normalButton.setOnMouseEntered(e -> normalButton.setStyle(hoverStyle));
    normalButton.setOnMouseExited(e -> normalButton.setStyle(normalStyle));
    normalButton.setOnMousePressed(e -> normalButton.setStyle(pressedStyle));
    normalButton.setOnMouseReleased(e -> normalButton.setStyle(hoverStyle));
  }


  /**
   * Method to style the Tic Tac Toe button.
   *
   * @param tttButton is the button to be styled
   */
  public static void styletttButton(Button tttButton) {
    String normalStyle =
        "-fx-background-color: white; "
            + "-fx-border-color: #cccccc; "
            + "-fx-border-width: 1px; "
            + "-fx-font-size: 75px; "
            + "-fx-text-fill: black;";

    tttButton.setStyle(normalStyle);
  }

  /**
   * Predefined style for the panel.
   */
  public static String panelStyle() {
    return "-fx-background-color: #586df8; -fx-background-radius: 10px;"
        + "-fx-border-color: #3a4dcf; -fx-border-radius: 10px; -fx-border-width: 5px;";
  }

  /**
   * Applies the panel style to the provided JavaFX node.
   *
   * @AI_Based This is based but not completely generated by the AI.
   *
   * @param node the node to apply the panel style to
   */
  public static void stylePanel(javafx.scene.Node node) {
    if (node == null) {
      throw new IllegalArgumentException("Node cannot be null");
    }
    node.setStyle(panelStyle());
  }
}